# Generated by Django 4.2.2 on 2023-06-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnswerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("uid", models.CharField(max_length=100)),
                ("ip", models.CharField(max_length=100)),
                ("user_agent", models.CharField(max_length=1000)),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("recaptcha_token", models.CharField(max_length=2000)),
                ("recaptcha_score", models.FloatField(null=True)),
                ("nickname", models.CharField(max_length=100)),
                ("question_id", models.IntegerField()),
                ("answer_id", models.IntegerField()),
                ("question_text", models.TextField()),
                ("answer_text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ResultEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("uid", models.CharField(max_length=100)),
                ("ip", models.CharField(max_length=100)),
                ("user_agent", models.CharField(max_length=1000)),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("recaptcha_token", models.CharField(max_length=2000)),
                ("recaptcha_score", models.FloatField(null=True)),
                ("nickname", models.CharField(max_length=100)),
                ("marks", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="StartEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("uid", models.CharField(max_length=100)),
                ("ip", models.CharField(max_length=100)),
                ("user_agent", models.CharField(max_length=1000)),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("country_code", models.CharField(max_length=100, null=True)),
                ("country_name", models.CharField(max_length=100, null=True)),
                ("province", models.CharField(max_length=100, null=True)),
                ("district", models.CharField(max_length=100, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                ("zip_code", models.CharField(max_length=100, null=True)),
                ("isp", models.CharField(max_length=1000, null=True)),
                ("recaptcha_token", models.CharField(max_length=2000)),
                ("recaptcha_score", models.FloatField(null=True)),
                ("nickname", models.CharField(max_length=100)),
            ],
        ),
    ]
