# Generated by Django 4.2.2 on 2023-06-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_uid_answerevent_device_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="startevent",
            name="job",
            field=models.IntegerField(
                choices=[
                    (1, "Medico"),
                    (2, "Professionista sanitario (inferiere, fisioterapista, ecc.)"),
                    (3, "Operatore socio-sanitario"),
                    (4, "Studente di medicina/odontoiatria"),
                    (5, "Studente di professioni sanitarie"),
                    (6, "Nessuna dei precedenti"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
