# Generated by Django 4.2.2 on 2023-06-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_startevent_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startevent",
            name="job",
            field=models.IntegerField(
                choices=[
                    (1, "Medico"),
                    (2, "Professionista sanitario (inferiere, fisioterapista, ecc.)"),
                    (3, "Operatore socio-sanitario"),
                    (4, "Studente di medicina/odontoiatria"),
                    (5, "Studente di professioni sanitarie"),
                    (6, "Nessuna delle precedenti"),
                ]
            ),
        ),
    ]
