# Generated by Django 4.2.2 on 2023-06-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_answerevent_job_resultevent_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerevent",
            name="job",
            field=models.IntegerField(
                choices=[
                    (1, "Medico/odontoiatra"),
                    (2, "Professionista sanitario (infermiere, fisioterapista, ecc.)"),
                    (3, "Operatore socio-sanitario"),
                    (4, "Studente di medicina/odontoiatria"),
                    (5, "Studente di professioni sanitarie"),
                    (6, "Altra tipologia di operatore sanitario"),
                    (7, "Non operatore sanitario"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="resultevent",
            name="job",
            field=models.IntegerField(
                choices=[
                    (1, "Medico/odontoiatra"),
                    (2, "Professionista sanitario (infermiere, fisioterapista, ecc.)"),
                    (3, "Operatore socio-sanitario"),
                    (4, "Studente di medicina/odontoiatria"),
                    (5, "Studente di professioni sanitarie"),
                    (6, "Altra tipologia di operatore sanitario"),
                    (7, "Non operatore sanitario"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="startevent",
            name="job",
            field=models.IntegerField(
                choices=[
                    (1, "Medico/odontoiatra"),
                    (2, "Professionista sanitario (infermiere, fisioterapista, ecc.)"),
                    (3, "Operatore socio-sanitario"),
                    (4, "Studente di medicina/odontoiatria"),
                    (5, "Studente di professioni sanitarie"),
                    (6, "Altra tipologia di operatore sanitario"),
                    (7, "Non operatore sanitario"),
                ]
            ),
        ),
    ]
