# Generated by Django 4.2.2 on 2023-06-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_answerevent_job_alter_resultevent_job_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerevent",
            name="device_type",
            field=models.IntegerField(
                choices=[(1, "Mobile"), (2, "Tablet"), (3, "Desktop"), (4, "Altro")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resultevent",
            name="device_type",
            field=models.IntegerField(
                choices=[(1, "Mobile"), (2, "Tablet"), (3, "Desktop"), (4, "Altro")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="startevent",
            name="device_type",
            field=models.IntegerField(
                choices=[(1, "Mobile"), (2, "Tablet"), (3, "Desktop"), (4, "Altro")],
                null=True,
            ),
        ),
    ]
