# Generated by Django 4.2.2 on 2023-06-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_answerevent_device_type_resultevent_device_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="startevent",
            name="referrer",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
