# Generated by Django 4.2.2 on 2023-06-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_startevent_referrer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startevent",
            name="referrer",
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
