# Generated by Django 4.2.5 on 2023-09-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_startevent_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerevent',
            name='device_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Mobile'), (2, 'Tablet'), (3, 'Desktop'), (4, 'Altro')], null=True),
        ),
        migrations.AlterField(
            model_name='answerevent',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answerevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerevent',
            name='recaptcha_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultevent',
            name='device_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Mobile'), (2, 'Tablet'), (3, 'Desktop'), (4, 'Altro')], null=True),
        ),
        migrations.AlterField(
            model_name='resultevent',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultevent',
            name='recaptcha_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='country_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='device_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Mobile'), (2, 'Tablet'), (3, 'Desktop'), (4, 'Altro')], null=True),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='isp',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='recaptcha_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='referrer',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
